export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_CATEGORIES = `SET_CATEGORIES`;
export const SET_QUESTION = `SET_QUESTION`;
export const SET_QUESTION_READY = `SET_QUESTION_READY`;
export const ADD_SCORE = `ADD_SCORE`;
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";
export const LOSE_LIFE = "LOSE_LIFE";
export const ADD_POINTS = "ADD_POINTS";
export const SET_DIFFICULTY = "SET_DIFFICULTY";

export const SET_HIGHSCORES = "SET_HIGHSCORES";
export const SET_HIGHSCORES_READY = "SET_HIGHSCORES_READY"
export const SET_HIGHSCORE_ADDED = "SET_HIGHSCORE_ADDED"
export const INIT_GLOBAL_STATE = "INIT_GLOBAL_STATE"
export const SET_IS_ENOUGH_FOR_HIGHSCORES = "SET_IS_ENOUGH_FOR_HIGHSCORES"