export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_CATEGORIES = `SET_CATEGORIES`;
export const SET_QUESTION = `SET_QUESTION`;
export const SET_QUESTION_READY = `SET_QUESTION_READY`;
export const ADD_SCORE = `ADD_SCORE`;
export const SET_CATEGORY_ID = "SET_CATEGORY_ID"